"""initial schema

Revision ID: 53d91ef43feb
Revises: 
Create Date: 2026-08-24 17:03:29.468838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53d91ef43feb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'club_lead', name='userrole'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('drafting', 'submitted', 'changes_requested', 'approved', 'rejected', name='clubstatus'), nullable=False),
    sa.Column('submitter_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.id'], name=op.f('fk_clubs_submitter_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clubs'))
    )
    op.create_table('requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('requirement_type', sa.Enum('constitution', 'exec_list', 'budget', 'advisor_form', 'bank_account_setup', 'exec_onboarding', name='requirement_type'), nullable=False),
    sa.Column('kind', sa.Enum('document', 'checklist', name='requirement_kind'), nullable=False),
    sa.Column('link_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'submitted', 'approved', 'rejected', name='requirement_status'), server_default='pending', nullable=False),
    sa.Column('reviewer_note', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_requirements_club_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirements')),
    sa.UniqueConstraint('club_id', 'requirement_type', name=op.f('uq_requirements_club_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requirements')
    op.drop_table('clubs')
    op.drop_table('users')
    # ### end Alembic commands ###
    sa.Enum(name='requirement_status').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='requirement_kind').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='requirement_type').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='clubstatus').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='userrole').drop(op.get_bind(), checkfirst=False)
