"""add club description and club_events

Revision ID: ea0b0ef2abf6
Revises: 2bc12142e507
Create Date: 2026-08-27 20:12:45.604479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ea0b0ef2abf6'
down_revision: Union[str, Sequence[str], None] = '2bc12142e507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('from_status', postgresql.ENUM('drafting', 'submitted', 'changes_requested', 'approved', 'rejected', name='clubstatus', create_type=False), nullable=True),
    sa.Column('to_status', postgresql.ENUM('drafting', 'submitted', 'changes_requested', 'approved', 'rejected', name='clubstatus', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_club_events_actor_id')),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_club_events_club_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_events'))
    )
    op.add_column('clubs', sa.Column('description', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'description')
    op.drop_table('club_events')
    # ### end Alembic commands ###
